FROM node:22-alpine AS build
WORKDIR /app

RUN corepack enable
ARG SUPABASE_URL
ARG SUPABASE_KEY
ARG SUPABASE_SERVICE_KEY
ARG NUXT_SUPABASE_URL
ARG NUXT_SUPABASE_KEY
ARG NUXT_SUPABASE_SERVICE_KEY
ENV SUPABASE_URL=${SUPABASE_URL}
ENV SUPABASE_KEY=${SUPABASE_KEY}
ENV SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
ENV NUXT_SUPABASE_URL=${NUXT_SUPABASE_URL}
ENV NUXT_SUPABASE_KEY=${NUXT_SUPABASE_KEY}
ENV NUXT_SUPABASE_SERVICE_KEY=${NUXT_SUPABASE_SERVICE_KEY}
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
COPY . ./
RUN pnpm run build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOST=0.0.0.0
COPY --from=build /app/.output ./.output

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
